import { spawn, execFileSync } from 'node:child_process';
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
const dir = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'orph-')), 'd');
const child = spawn(process.execPath, ['--input-type=module', '-e', `import { chromium } from 'patchright'; await chromium.launchPersistentContext(${JSON.stringify(dir)}, { headless: true }); console.log('up'); setInterval(()=>{},1e6);`], { stdio: ['ignore', 'pipe', 'inherit'] });
await new Promise((r) => child.stdout.once('data', r));
execFileSync('taskkill', ['/PID', String(child.pid), '/F']);
await new Promise((r) => setTimeout(r, 1500));
const out = execFileSync('powershell.exe', ['-NoProfile', '-Command', `Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like '*orph-*' } | Select-Object ProcessId,ParentProcessId,Name,@{n='c';e={$_.CommandLine.Substring(0,[Math]::Min(300,$_.CommandLine.Length))}} | ConvertTo-Json`], { encoding: 'utf8' });
console.log('dir =', dir); console.log(out.slice(0, 1500));
execFileSync('powershell.exe', ['-NoProfile', '-Command', `Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like '*orph-*' -and $_.Name -notlike 'powershell*' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }`]);
